
common : [[
#define MULTISCATAPPROX_ENABLED 
//#define FASTSKY_ENABLED
//#define FASTAERIALPERSPECTIVE_ENABLED
//#define MULTISCATAPPROX_ENABLED
//#define SHADOWMAP_ENABLED  
//#define MULTI_SCATTERING_POWER_SERIE
#define RENDER_SUN_DISK 
#define USE_CornetteShanks
#define NONLINEARSKYVIEWLUT
]]
